var express = require('express');
const bodyParser = require('body-parser');
var User = require('../models/user');
var passport = require('passport');
var authenticate = require('../authenticate');
const cors = require('./cors');
const crypto = require('crypto');
const mailer = require('../mailer');

var router = express.Router();
router.use(bodyParser.json());



router.options('*', cors.corsWithOptions, (req, res) => { res.sendStatus(200); })

/* GET users listing. */
router.get('/', cors.corsWithOptions, authenticate.verifyUser, authenticate.verifyAdmin, function(req, res, next) {
  User.find({})
  .then((users) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.json(users)
  })
  .catch((err) => next(err));
});

router.post('/signup', cors.corsWithOptions, function(req, res, next){ //explicit function, analogue to arrow function (see below)
  User.register(new User({username: req.body.username}), req.body.password, (err, user) => {
    if(err){
      res.statusCode = 500;
      res.setHeader('Content-Type', 'application/json');    
      res.json({err: err});
    }
    else{
      if(req.body.firstname){
        user.firstname = req.body.firstname;
      }
      if(req.body.lastname){
        user.lastname = req.body.lastname;
      }
      if(req.body.email){
        user.email = req.body.email.toLowerCase().trim();
      }
      user.save()
        .then((savedUser) => {
          passport.authenticate('local')(req, res, () => { //no error handling needed, authenticate() directly send back error response if authentication fails
            res.statusCode = 200;
            res.setHeader('Content-Type', 'application/json');
            res.json({success: true, status: 'Registration succesful', user: savedUser});
          });
        })
        .catch((err) => {
          res.statusCode = 500;
          res.setHeader('Content-Type', 'application/json');
          res.json({err: err});
        });
    }
  }, (err) => console.log(err));  
});

router.post('/login', cors.corsWithOptions, async (req, res, next) => {
  // Allow login with email: resolve to username before passport authenticates
  const loginField = req.body.username;
  if (loginField && loginField.includes('@')) {
    try {
      const user = await User.findOne({ email: loginField.toLowerCase().trim() });
      if (user) req.body.username = user.username;
    } catch (err) {
      return next(err);
    }
  }
  passport.authenticate('local', (err, user, info) => {
    if(err){
      return next(err);
    }
    if(!user){
      res.statusCode = 401;
      res.setHeader('Content-Type', 'application/json');
      return res.json({success: false, status: 'Login unsuccesful!', err: info});
    }
    req.logIn(user, { session: false }, (err) => {
      if(err){        
        res.statusCode = 401;
        res.setHeader('Content-Type', 'application/json');
        res.json({success: false, status: 'Login unsuccesful!', err: 'Could not log in user!'});
      }
      else{
        var token = authenticate.getToken({_id: req.user._id});
        res.statusCode = 200;
        res.setHeader('Content-Type', 'application/json');
        res.json({success: true, token: token, status: 'You are successfully logged in', isAdmin: req.user.admin});
      }
    });
  }) (req, res, next);
});

router.get('/logout', cors.corsWithOptions, (req, res, next) => {
  if(req.session){
    req.session.destroy(); //remove session information on the server side
    res.clearCookie('session-id'); //asks the client to remove the related cookie
    res.redirect('/');
  }
  else{
    var err = new Error('You are not logged in');
    err.status = 403;
    next(err);
  }
});


const getSessionToken = (req, res, next) => {  
  if(req.user){
    var token = authenticate.getToken({_id: req.user._id}); //after oauth authentication, token is generated by the server and used for subsequent operations, as happened with local login
    res.statusCode = 200;
    res.setHeader('Content-Type', 'application/json');
    res.json({success: true, token: token, status: 'You are succesfully logged in!'});
  }else{    
    next(err);
  }
};


//router.get('/facebook/token', passport.authenticate('facebook-token'), getSessionToken);
//router.get('/google/token', passport.authenticate('google', { scope: ['https://www.googleapis.com/auth/plus.login']}), getSessionToken);


router.get('/refresh-token', cors.corsWithOptions, authenticate.verifyUser, (req, res) => {
    const token = authenticate.getToken({ _id: req.user._id });
    res.json({ success: true, token });
});

router.get('/checkJWTToken', cors.corsWithOptions, (req, res) => {
  passport.authenticate('jwt', {session: false}, (err, user, info) => {
    if(err){
      return next(err);
    }
    if(!user){
      res.statusCode = 401;
      res.setHeader('Content-Type', 'application/json');
      return res.json({status: 'JWT Invalid', success: false, err: info});
    }
    else{
      res.statusCode = 200;
      res.setHeader('Content-Type', 'application/json');
      return res.json({status: 'JWT Valid', success: true, user: user});
    }
  }) (req, res);
})

// POST /users/reset-request  { email }
router.post('/reset-request', cors.corsWithOptions, async (req, res, next) => {
    try {
        const { email } = req.body;
        if (!email) {
            return res.status(400).json({ success: false, err: 'Email richiesta' });
        }
        const user = await User.findOne({ email: email.toLowerCase().trim() });
        // Always respond 200 to avoid leaking whether email is registered
        if (!user) {
            return res.json({ success: true, status: 'Se l\'email è registrata, riceverai un link per il reset' });
        }
        const token = crypto.randomBytes(32).toString('hex');
        user.resetPasswordToken = token;
        user.resetPasswordExpires = new Date(Date.now() + 3600000); // 1 hour
        await user.save();
        try {
            await mailer.sendPasswordReset(user.email, token);
        } catch (mailErr) {
            console.error('Mailer error:', mailErr.message);
        }
        res.json({ success: true, status: 'Se l\'email è registrata, riceverai un link per il reset' });
    } catch (err) {
        next(err);
    }
});

// POST /users/reset-password  { token, newPassword }
router.post('/reset-password', cors.corsWithOptions, async (req, res, next) => {
    try {
        const { token, newPassword } = req.body;
        if (!token || !newPassword) {
            return res.status(400).json({ success: false, err: 'Token e nuova password richiesti' });
        }
        const user = await User.findOne({
            resetPasswordToken: token,
            resetPasswordExpires: { $gt: new Date() }
        });
        if (!user) {
            return res.status(400).json({ success: false, err: 'Token non valido o scaduto' });
        }
        await user.setPassword(newPassword);
        user.resetPasswordToken = null;
        user.resetPasswordExpires = null;
        await user.save();
        res.json({ success: true, status: 'Password aggiornata con successo' });
    } catch (err) {
        next(err);
    }
});

// GET /users/preferences
router.get('/preferences', cors.corsWithOptions, authenticate.verifyUser, (req, res, next) => {
    const { imdbEnabled, letterboxdEnabled, letterboxdUsername, preferredCalendar, autoSwitchTab, email } = req.user;
    res.json({ imdbEnabled, letterboxdEnabled, letterboxdUsername, preferredCalendar: preferredCalendar || '', autoSwitchTab: autoSwitchTab !== false, email: email || '' });
});

// PUT /users/preferences  { imdbEnabled, letterboxdEnabled, letterboxdUsername }
router.put('/preferences', cors.corsWithOptions, authenticate.verifyUser, async (req, res, next) => {
    try {
        const { imdbEnabled, letterboxdEnabled, letterboxdUsername, preferredCalendar, autoSwitchTab } = req.body;
        const user = await User.findById(req.user._id);
        if (imdbEnabled !== undefined) user.imdbEnabled = imdbEnabled;
        if (letterboxdEnabled !== undefined) user.letterboxdEnabled = letterboxdEnabled;
        if (letterboxdUsername !== undefined) user.letterboxdUsername = letterboxdUsername.trim();
        if (preferredCalendar !== undefined) user.preferredCalendar = preferredCalendar;
        if (autoSwitchTab !== undefined) user.autoSwitchTab = autoSwitchTab;
        await user.save();
        res.json({ imdbEnabled: user.imdbEnabled, letterboxdEnabled: user.letterboxdEnabled, letterboxdUsername: user.letterboxdUsername, preferredCalendar: user.preferredCalendar, autoSwitchTab: user.autoSwitchTab });
    } catch (err) {
        next(err);
    }
});

module.exports = router;
